
import type { Metadata } from "next";
import {ReactNode} from "react";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/nav/TopNav";
import SideMenu from "@/components/SideMenu";


export const metadata: Metadata = {
  title: "Overflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
        suppressHydrationWarning
      lang="en" className="h-full">
      <body className="flex flex-col h-screen bg-stone-200 dark:bg-neutral-900">
        <Providers>
          <TopNav />
          <div className="flex grow overflow-auto">
            <aside className="basis-1/6 shrink-0 border-r border-neutral-500 pt-20 sticky top-0 px-6">
              <SideMenu/>
            </aside>
            <main className="flex-1 pt-20 h-full">
              {children}
            </main>
            <aside className="basis-1/4 shrink-0 border-l bg-stone-300 dark:bg-neutral-700 pt-20 sticky top-0 px-6">
              right content
            </aside>
          </div>
        </Providers>
      </body>
    </html>
  );
}
